-- The Salty Baker v4 Orders table
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_date date not null default current_date,
  pickup_date date,
  customer_name text not null,
  media_source text,
  details text,
  payment_type text,
  total_amount numeric(12,2) not null default 0,
  status text not null default 'Open',
  photo_data text,
  posted_transaction_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_pickup on public.orders(pickup_date);
create index if not exists idx_orders_customer on public.orders(customer_name);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at before update on public.orders
for each row execute function public.set_updated_at();

alter table public.orders enable row level security;

drop policy if exists "Allow public read orders" on public.orders;
drop policy if exists "Allow public insert orders" on public.orders;
drop policy if exists "Allow public update orders" on public.orders;
drop policy if exists "Allow public delete orders" on public.orders;

create policy "Allow public read orders" on public.orders for select using (true);
create policy "Allow public insert orders" on public.orders for insert with check (true);
create policy "Allow public update orders" on public.orders for update using (true) with check (true);
create policy "Allow public delete orders" on public.orders for delete using (true);

select 'Orders table ready.' as status;
